upstream backend-cluster {
    least_conn;
    server nginx-app1:80;
    server nginx-app2:80;
    server nginx-app3:80;
    keepalive 32;
}

server {
    listen 80 default_server;
    server_name _;  # Принимаем любые запросы

    location / {
        proxy_pass http://backend-cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_connect_timeout 5s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        
        # Важно для сессий
        proxy_set_header Cookie $http_cookie;
    }
}